sudo: required
dist: trusty
language: python
python:
    - "3.5"
env:
    - AF_PATH=$HOME/TryOutTravis/arrayfire-3
    - LD_LIBRARY_PATH="$AF_PATH/lib"
    - PYTHON_PATH="$HOME/Bolt/:$PYTHON_PATH"

# command to install dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential git cmake libfreeimage-dev cmake-curses-gui
    - sudo apt-get install -qq libopenblas-dev libfftw3-dev liblapacke-dev libboost-all-dev
    - sudo apt-get install -qq libfontconfig1-dev
    - echo | sudo apt-add-repository ppa:keithw/glfw3
    - sudo apt-get update
    - sudo apt-get install libglfw3
    - git clone https://github.com/arrayfire/arrayfire.git
    - cd arrayfire
    - git submodule init
    - git submodule update
    - mkdir build 
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=package
    - make -j2
    - make test 
    - make install
    - cd $HOME/TryOutTravis
    - wget http://arrayfire.s3.amazonaws.com/3.5.0/ArrayFire-v3.5.0_Linux_x86_64.sh
    - yes | bash ArrayFire-v3.5.0_Linux_x86_64.sh
    - export LD_LIBRARY_PATH=$HOME/TryOutTravis/arrayfire-3/lib:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=$HOME/TryOutTravis/arrayfire/build/package/lib:$LD_LIBRARY_PATH

install:
    - pip install arrayfire

script:
    python -m arrayfire.tests